const LEVELS = {
  "CVC": [
    "cat","bat","rat","mop","hat","van","can","fan","man","pan",
    "bag","tag","jam","ham","cap","lap","map","nap","pen","sat",
    "bed","red","hen","ten","net","pet","jet","web","leg","men",
    "den","get","set","wet","vet","pig","big","wig","dig","bin",
    "pin","tin","win","bit","hit","sit","lip","tip","zip","dog",
    "log","fox","hot","hop","top","pot","cup","bug","sun","run"
  ],
  "CCVC": [
    "clam","clap","clip","clan","clog","crab","crop","cram","drip","drop",
    "drum","drag","drab","flat","flag","flip","flop","frog","fret","glad",
    "glum","grip","grin","grit","grab","plan","plop","plum","plug","prop",
    "snag","snap","snip","snug","skip","skim","skid","slip","sled","slim",
    "spin","spit","spot","step","stem","stop","stub","stun","swim","trip",
    "trim","trap","trot","trek","twin","twig","brim","brag","tram","slug"
  ],
  "CVCC": [
    "lamp","belt","fist","pond","mask","dusk","melt","jump","hand","wind",
    "nest","camp","list","golf","dump","band","bend","bond","land","sand",
    "send","fund","find","kind","mind","best","bust","dust","fast","gust",
    "just","last","lost","must","rest","bump","damp","hump","limp","pump",
    "ramp","felt","salt","tilt","milk","silk","task","tusk","risk","gift",
    "lift","soft","rent","tent","mint","hunt","hint","dent","vest","west"
  ],
  "Silent-E": [
    "cake","bike","rope","cube","pine","mole","lane","dune","kite","vote",
    "tune","gate","home","rule","hive","bake","lake","make","take","wake",
    "came","game","name","same","wave","base","race","date","late","cape",
    "like","hike","wide","hide","ride","dine","fine","mine","vine","tire",
    "hope","note","bone","cone","code","coke","hole","pole","dose","rose",
    "cute","mute","fume","tube","rude","lure","cure","pure","page","wade"
  ],
  "Vowel Teams": [
    "rain","boat","feet","goat","read","coat","heat","sail","beam","seem",
    "tail","road","seed","leaf","load","day","bay","hay","lay","pay",
    "say","way","play","stay","tray","clay","mail","pail","rail","hail",
    "bean","deal","heal","lean","meat","neat","seal","team","bee","see",
    "tree","feel","heel","need","week","soap","toad","foam","oak","toast",
    "book","cook","foot","look","moon","pool","room","tool","wood","zoo"
  ],
  "R-Controlled": [
    "star","bird","horn","fern","curl","bark","fort","burn","dirt","corn",
    "farm","girl","pork","herb","surf","bar","car","far","jar","tar",
    "barn","card","dark","hard","harm","mark","park","part","scar","yarn",
    "her","herd","term","verb","sir","stir","firm","born","cord","ford",
    "fork","form","more","port","sort","torn","word","work","worn","norm",
    "fur","hurt","turn","purr","yard","lark","mart","harp","worm","tarp"
  ],
  "Sentences": [
    "The cat sat.",
    "A dog ran.",
    "The hen hops.",
    "A pig is big.",
    "The sun is hot.",
    "A bug is red.",
    "I see a cat.",
    "I can hop.",
    "The fox ran.",
    "A hat is red.",
    "I am big.",
    "The rat ran.",
    "I see a dog.",
    "A fat cat sat.",
    "The cup is big.",
    "I can run.",
    "The dog digs.",
    "I see a hen.",
    "A wet dog.",
    "The pig digs.",
    "I can dig.",
    "A bat can fly.",
    "The man ran.",
    "I see a bug.",
    "A big red bag.",
    "The cub sits.",
    "I can sit.",
    "A hen and a pig.",
    "The bug is in it.",
    "I see the sun.",
    "A cat and a dog.",
    "The map is big.",
    "I can jump.",
    "The fox can run.",
    "I see a red hat.",
    "A dog can sit.",
    "I am a kid.",
    "A cat ran fast.",
    "The hen sat down.",
    "I can see it."
  ]
};
